dist: xenial
language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
install:
  - pip install -q "pytest>=3.6"
  - pip install -q pytest-flask
  - pip install -q pytest-cov coveralls
  - pip install -e .
script:
  - py.test --cov=flask_executor/ tests/ .
after_success:
  - coveralls
